package il.ac.shenkar.costManager;

import java.util.ArrayList;
import java.util.Collection;

/**
 * The Class User.
 */
public class User {
    private String name;
    private int userId;
    private ArrayList<Item> items;

    @Override
    public String toString() {
        return "User{" +
                "name='" + name + '\'' +
                ", userId=" + userId +
                '}';
    }

    /**
     * Instantiates a new user.
     *
     * @param name   the name of the user
     * @param userId the user id of the user (unique). It is used to identify the user. For new users, the user id will be generated by the system.
     */
    public User(String name, int userId) {
        this.name = name;
        this.userId = userId;
        this.items = new ArrayList<>();
    }

    /**
     * Returns the name of the user.
     *
     * @return the name of the user
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the name of the user.
     *
     * @param name the new name of the user
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Returns the user id of the user.
     *
     * @return the user id of the user
     */
    public int getUserId() {
        return userId;
    }

    /**
     * Sets the user id of the user.
     *
     * @param userId the new user id of the user
     */
    public void setUserId(int userId) {
        this.userId = userId;
    }

    /**
     * Returns the items of the user.
     *
     * @return the items of the user
     */
    public ArrayList<Item> getItems() {
        return items;
    }

    /**
     * Sets the items of the user.
     *
     * @param items the new items of the user
     */
    public void setItems(ArrayList<Item> items) {
        this.items = items;
    }
}
