version: '3.1'

services:
  db:
    image: mariadb:10.3
    restart: always
    ports:
      - 1234:3306
    environment:
      MYSQL_ROOT_PASSWORD: 1

  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
